//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPmockDB.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            Asset_ID = Guid.NewGuid();
        }
        public System.Guid Asset_ID { get; set; }
        public int Asset_nbShare { get; set; }
        public string Asset_ticker { get; set; }
        public System.DateTime Asset_AQS_date { get; set; }
        public float Asset_shareCost { get; set; }
        public System.Guid Portfolio_ID { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
    }
}
